# Generated by Django 4.0.4 on 2022-12-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=122)),
                ('address', models.CharField(blank=True, max_length=122, null=True)),
                ('description', models.CharField(max_length=122)),
                ('skill_1', models.CharField(max_length=122)),
                ('skill_2', models.CharField(max_length=122)),
                ('skill_3', models.CharField(max_length=122)),
                ('skill_4', models.CharField(max_length=122)),
                ('skill_5', models.CharField(blank=True, max_length=122, null=True)),
                ('skill_6', models.CharField(blank=True, max_length=122, null=True)),
                ('skill_1_title', models.CharField(max_length=122)),
                ('skill_1_duration', models.CharField(max_length=122)),
                ('skill_1_description', models.CharField(max_length=122)),
                ('skill_2_title', models.CharField(blank=True, max_length=122, null=True)),
                ('skill_2_duration', models.CharField(blank=True, max_length=122, null=True)),
                ('skill_2_description', models.CharField(blank=True, max_length=122, null=True)),
                ('education_10th_year', models.CharField(max_length=122)),
                ('education_10th_uni', models.CharField(max_length=122)),
                ('education_10th_score', models.CharField(max_length=122)),
                ('education_12th_year', models.CharField(max_length=122)),
                ('education_12th_uni', models.CharField(max_length=122)),
                ('education_12th_score', models.CharField(max_length=122)),
                ('education_btech_year', models.CharField(max_length=122)),
                ('education_btech_uni', models.CharField(max_length=122)),
                ('education_btech_score', models.CharField(max_length=122)),
                ('education_mtech_year', models.CharField(blank=True, max_length=122, null=True)),
                ('education_mtech_uni', models.CharField(blank=True, max_length=122, null=True)),
                ('education_mtech_score', models.CharField(blank=True, max_length=122, null=True)),
            ],
        ),
    ]
