# Generated by Django 4.0.4 on 2022-12-04 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumesite', '0002_alter_user_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='std',
        ),
    ]
