# Generated by Django 3.2.16 on 2022-12-05 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumesite', '0003_rename_user_std'),
    ]

    operations = [
        migrations.RenameField(
            model_name='std',
            old_name='skill_1_description',
            new_name='exp_1_description',
        ),
        migrations.RenameField(
            model_name='std',
            old_name='skill_1_duration',
            new_name='exp_1_duration',
        ),
        migrations.RenameField(
            model_name='std',
            old_name='skill_1_title',
            new_name='exp_1_title',
        ),
        migrations.RenameField(
            model_name='std',
            old_name='skill_2_description',
            new_name='exp_2_description',
        ),
        migrations.RenameField(
            model_name='std',
            old_name='skill_2_duration',
            new_name='exp_2_duration',
        ),
        migrations.RenameField(
            model_name='std',
            old_name='skill_2_title',
            new_name='exp_2_title',
        ),
    ]
