# Generated by Django 4.0.4 on 2022-12-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumesite', '0004_auto_20221206_0050'),
    ]

    operations = [
        migrations.CreateModel(
            name='resume',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
